development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:eeed328023954a1071be2e6d5fd146f2@dory.redistogo.com:10265/
  channel_prefix: hot_talks_api_production
